[package]
name = "luz"
version = "0.1.0"
authors = ["Arthur Canido Regueira de Miranda"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
